// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	addMagnet: (uri: string) => typedError<AddTorrentResult, string>(__TAURI_INVOKE("add_magnet", { uri })),
	addTorrentFile: (bytes: number[]) => typedError<AddTorrentResult, string>(__TAURI_INVOKE("add_torrent_file", { bytes })),
	listTorrents: () => typedError<TorrentSnapshot, string>(__TAURI_INVOKE("list_torrents")),
	pause: (id: number) => typedError<null, string>(__TAURI_INVOKE("pause", { id })),
	resume: (id: number) => typedError<null, string>(__TAURI_INVOKE("resume", { id })),
	forget: (id: number) => typedError<null, string>(__TAURI_INVOKE("forget", { id })),
	delete: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete", { id })),
	sessionStats: () => typedError<SessionStats, string>(__TAURI_INVOKE("session_stats")),
	getTorrentDetail: (id: number) => typedError<TorrentDetail, string>(__TAURI_INVOKE("get_torrent_detail", { id })),
	setOnlyFiles: (id: number, fileIdxs: number[]) => typedError<null, string>(__TAURI_INVOKE("set_only_files", { id, fileIdxs })),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
};

/** Events */
export const events = {
	sessionStatsEvent: makeEvent<SessionStatsEvent>("session-stats-event"),
	torrentsSnapshotEvent: makeEvent<TorrentsSnapshotEvent>("torrents-snapshot-event"),
};

/* Types */
export type AddTorrentResult = {
	id: number | null,
	info_hash: string,
	name: string | null,
};

export type AppSettings = {
	// Empty string -> resolve to ~/Downloads/BlackHand.
	download_dir: string,
	// 0 (either side) -> use librqbit defaults.
	listen_port_min: number,
	listen_port_max: number,
	enable_upnp: boolean,
	enable_dht: boolean,
	// 0 -> unlimited.
	upload_limit_kbps: number,
	download_limit_kbps: number,
};

export type SessionStats = {
	down_bps: number,
	up_bps: number,
	fetched_bytes: number,
	uploaded_bytes: number,
	peers_live: number,
	uptime_secs: number,
};

export type SessionStatsEvent = SessionStats;

export type TorrentDetail = {
	id: number,
	info_hash: string,
	name: string | null,
	output_folder: string,
	state: TorrentState,
	finished: boolean,
	progress_bytes: number,
	uploaded_bytes: number,
	total_bytes: number,
	progress_pct: number,
	error: string | null,
	files: TorrentFile[],
};

export type TorrentFile = {
	// Position in the torrent's file table — the value used by `set_only_files`.
	idx: number,
	name: string,
	components: string[],
	length: number,
	included: boolean,
};

export type TorrentSnapshot = {
	torrents: TorrentSummary[],
};

export type TorrentState = "initializing" | "live" | "paused" | "error";

export type TorrentSummary = {
	id: number,
	info_hash: string,
	name: string | null,
	output_folder: string,
	state: TorrentState,
	finished: boolean,
	progress_bytes: number,
	uploaded_bytes: number,
	total_bytes: number,
	// 0.0 .. 100.0
	progress_pct: number,
	down_bps: number,
	up_bps: number,
	peers_live: number,
	eta_secs: number | null,
	error: string | null,
};

export type TorrentsSnapshotEvent = TorrentSnapshot;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

